on:
  push:
    branches:
      - "main"
name: Build and Deploy
jobs:
  buildDockerImage:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Get short SHA
        id: sha
        run: |
          echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: Build and push image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: acrogenesis
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          image_name: nerves-hub-web
          image_tag: "latest,${{ steps.sha.outputs.sha7 }}"
      - name: Save DigitalOcean kubeconfig
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Deploy to DigitalOcean Kubernetes
        run: |
          sed -i "s+TAG+$(echo ${{ github.sha }} | head -c7)+g" ${GITHUB_WORKSPACE}/deploy.yaml
          sed -i "s+HOSTNAME+${{ secrets.HOSTNAME }}+g" ${GITHUB_WORKSPACE}/deploy.yaml
          doctl kubernetes cluster kubeconfig save ${{ secrets.CLUSTER_NAME }}
          kubectl apply -f ${GITHUB_WORKSPACE}/deploy.yaml
      - name: Verify deployment
        run: kubectl rollout status deployment/nerves-hub-web
